sudo: true
dist: trusty
group: deprecated-2017Q4
language: node_js
node_js:
- '8'
- '10'
before_script:
- npm install
script:
- npm test
after_success: npm run coverage
jobs:
  include:
  - stage: build docker image
    script:
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker build -f Dockerfile-core -t docker.io/hewlettpackardenterprise/core-hubot:latest .
    - docker images
    - docker tag hewlettpackardenterprise/core-hubot docker.io/hewlettpackardenterprise/core-hubot:latest
    - docker push docker.io/hewlettpackardenterprise/core-hubot:latest
    - docker build -t docker.io/hewlettpackardenterprise/hpe-oneview-hubot:latest .
    - docker images
    - docker tag hewlettpackardenterprise/hpe-oneview-hubot docker.io/hewlettpackardenterprise/hpe-oneview-hubot:latest
    - docker push docker.io/hewlettpackardenterprise/hpe-oneview-hubot:latest
env:
  global:
  - secure: wHn6wY5QlenoSMJwpEmCourbh3Y2XenLG6ZLZedDGxwETiE6dK2sa634CAczFBRP5LqFdOi4+VRYvHYEpJi7b7lqi1X3Dm0ljt0StUwj8tu2rSCk+kAy7/sYcJy1BHNYaAgQ81SCIhANMmPRF82FLTOqDFi6Dj2SQYwny1UnNfVnB1ZdXkkeeMxRCmEQe3x2LqU3UFvDv3qEIbV9s+dcBXBPu7DvfYRlYgiw3CimnE6L843zjsozVuGEyng1gShLbgAJ84NDUJdm3HBlneq8k+kgDgk+3DPJ3goRdLQ7a34vZLRUlisIoZIjd0BTe4Ntv0uMKEBrIs9MtUliLjpy6/0pedOLd2pLkgIwbWqevh0nwJSdHx92DkbaIrgbE38VOET5j75eQS+i3kvtMwR1taroWKE9SVI0X4McqEiOQNI0SFIMSpDkyARJ3TZafeV+pxRl9CQ1ZROMrdN4SJYxoux5/3A9DoOC8jknwfs47y0WotiTmg6oMqokeZXPFuGHdyKwDWSU/9IVWkAD22Ea8JEapOlcl7TU2Q3XqHweq+jK7k0qtXIGBMywGXvPDV4W0i3gL7+v+VS2ufDdwdsE7aeI2O/j3ExPhj0V15M76n4J92tbL++DeeZLekFcgm6bQydQ/o1X6sly8tIbVRXpB0BQrcmpFQ50NTbiIELEBBc=
  - secure: VXLTTSc0CPA1Ws0gH4lKbN8wlyJoOTwQf/TJ5gC/xcC//EAm2fpqOhg2kIPpcxPEaKNtqVMRNIywIvIVCypTQlZEwHV9f93lRztktr8mxjnQ7EyD+Mi86JNH+tY2jutTC+8B4yg9cjVDIxjLS5BkvyIGU7T54bjLkpBK9Ku5gMOhLSsAJxnONCSMm+VImWtsfk87Xzb/GxwgAlZQhrYJ153otYoN+tMOVeDnOKMW581pbs8aK5KYPegacXioHG5KsJbFVlVPi5D98Wbrvtyxtv4cahYh1MHfDs5ZjXkzz2aWq/23M8554l3MRUeb/TFbMOA7gWCRwGoH0A5H3PkJYtz7xrnMTqnhBcEESmEhoXCPnD1OzQJY239kEMiRkdYfxqvCgfSsXHhCkJVRqC+Dw87l1V/hKLfbUHRMoxPGgu14U1IiWczW4y9Ic3stahjwPdVluV00d07tZB/DZUrQs3Hx019Eoo8xDmfFPGlVzylCfgdX+KD6r+yOC4ojYERLwMt+LQn5v5EkIOBF1lTwMVb2rawh5b5uPHDdV8VQ80LraGDZh0pW544kNS7x6JrEL0rRbzUgluVqpYlck/viN/xKnfLWQuf/DQKKKrke9fvIGrRAd6bA+weRbNOJwTXJmd4+AcDf6SDrILt3INJAzjWomm89hRGPkVgbVnW1EGo=
